{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "default" .Values.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
