name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/946678058338/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-sa@dev-project-490411.iam.gserviceaccount.com

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Validate HTML exists
      run: |
        if [ ! -f index.html ]; then
          echo "index.html not found!"
          exit 1
        fi

    - name: Basic HTML check
      run: |
        grep "<html" index.html || (echo "Invalid HTML file" && exit 1)

    - name: Build Image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ vars.PROJECT_ID }}/myartifactregistry/gcp-test:${{ github.sha }} .

    - name: Push Image
      run: |
        docker push us-central1-docker.pkg.dev/${{ vars.PROJECT_ID }}/myartifactregistry/gcp-test:${{ github.sha }}
